repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        args:
          - --install-types
          - --non-interactive
          - --config-file=.mypy.ini

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args:
          - -x

  - repo: https://github.com/zahorniak/pre-commit-circleci.git
    rev: v0.6
    hooks:
      - id: circleci_validate

  - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.6
    hooks:
      - id: add-msg-issue-prefix
