version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.6.9
  general: bjd2385/general@dev:b2125b3ad7c8ba80b52e2249516e418c1b245fea
  slack: circleci/slack@4.12.1


workflows:
  wildmatch:
    jobs:
      - dynamic/continue:
          context: orb-publishing

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          name: GitHub release
          context: github
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/python-release-poetry:
          name: pypi upload
          context: pypi
          repository: python
          requires:
            - request-approval
          username: $PYPI_USERNAME
          password: $API_TOKEN
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/